### PR TITLE
Low level replication API

### PR DESCRIPTION
**Pull request by ivelten**
This PR is meant to provide a low level replication API to be used internally for a high level, user API.

### CODE REVIEW

**Comment by SeanFarrow** [comment]
Can you merge this on to the replication branch please?
Also, I'm not sure we need a lsn type, I think one exists.
How do you see this being used for replication?

**Comment by ivelten** [comment]
Is there a type for Log Sequential Number?

I think LSN can be useful when we want to specify the WAL position from where to start. It is not a common case, but if we want to use that sometime, we would need to enter the wal position using a value that is expressed by this type.

Having said that, I think those types can be adjusted to better serve what we can implement in the high-level API. Also, I think we should support both sync and async uses of it too.

**Comment by SeanFarrow** [comment]
OK, I've just looked at this, I'm not sure where the RawReplicationStream is going to come in useful, is this for physical or logical replication?

The NpgSqlLsn type is definitely useful though, as I can't seem to find it anywhere else--can we have some tests though?

Can you revert the pr on the replication branch, as I need to finish the high level api, then I can start integrating the changes. There will be separate types for physical and logical replication, both using an abstract base class, these types can be obtained from an existing connection using an extension method and a factory.

**Comment by ivelten** [comment]
@SeanFarrow I just made tests for the NpgsqlLsn type. The RawReplicationStream was meant primarily to be used to read the replication data (for example, as a text using a `StreamReader`). I thought it could be of use internally to enter the copy mode and start receiving the replication. If you are already writing it in some other way, then i think we can discard it.

I think I can write some other tests for the message types though. Will do it and reopen the pull request.

**Comment by SeanFarrow** [comment]
Ok, thanks.
I need to think through the high level api, as we don’t want to use npgsqlConnection at all.
Give me a couple of days—I’ll come back to you, my main need is for you to revert the pr as it’s blocking me right now.

**Pull request merged**
